STREAMLINK_BINARY = "streamlink"

# recheck every minute
RECHECK_CHANNEL_STATUS_TIME = 60

TIME_NICE_FORMAT = "%Y%m%d_%H%M%S"

TEMP_FILE_EXT = ".sapart"

STDOUT_READ_NEXT_LINE_TIMEOUT = 0.5

LOG_LEVEL_DEFAULT = "INFO"


# Rclone defaults

RCLONE_BIN_LOCATION = "rclone"
RCLONE_CONFIG_LOCATION = ""
RCLONE_DEFAULT_TRANSFERS = 4
RCLONE_DEFAULT_OPERATION = "move"