STREAMLINK_BINARY = "streamlink"

# recheck every minute
RECHECK_CHANNEL_STATUS_TIME = 60

TIME_NICE_FORMAT = "%Y%m%d_%H%M%S"

TEMP_FILE_EXT = ".sapart"

STDOUT_READ_NEXT_LINE_TIMEOUT = 0.5

LOG_LEVEL_DEFAULT = "INFO"