STREAMLINK_BINARY = "streamlink"

# recheck every minute
RECHECK_CHANNEL_STATUS_TIME = 60

TIME_NICE_FORMAT = "%Y%m%d_%H%M%S"

TEMP_FILE_EXT = ".sapart"

STDOUT_READ_NEXT_LINE_TIMEOUT = 0.5

LOG_LEVEL_DEFAULT = "INFO"

# Stream archiver defaults

STREAM_SPLIT_TIME = 3600
STREAM_DEFAULT_NAME = "unknown_stream"
STREAM_DEFAULT_QUALITY = "best"
# Rclone defaults

RCLONE_BIN_LOCATION = "rclone"
RCLONE_CONFIG_LOCATION = ""
RCLONE_DEFAULT_TRANSFERS = 4
RCLONE_DEFAULT_OPERATION = "move"


# config stuff

STREAMERS_REQUIRED_FIELDS = {

    'url': str,

}

DEFAULT_DOWNLOAD_DIR = "."