FROM alpine:latest
MAINTAINER colethedj <colethedj@protonmail.com>

COPY . /saa
RUN apk update && \
    apk add ffmpeg \
    python3 \
    python3-dev \
    py-pip \
    ca-certificates \
    libc-dev \
    wget \
    git \
    gcc && \
    pip3 install -r /saa/requirements.txt -U && \
    wget https://downloads.rclone.org/rclone-current-linux-amd64.zip && \
    unzip rclone-current-linux-amd64.zip && \
    cd rclone-*-linux-amd64 && \
    cp rclone /usr/bin/ && \
    cd / && \
    rm rclone-current-linux-amd64.zip && \
    rclone --version && \
    git clone https://github.com/streamlink/streamlink.git && \
    git clone https://gitlab.com/colethedj/streamlink-saa-patches.git && \
    cd streamlink && \
    for p in ../streamlink-saa-patches/patches/*.patch; do git apply --whitespace=fix --reject < $p; done && \
    pip3 uninstall streamlink -y && pip3 install . && \
    cd / && \
    rm -rf /streamlink && rm -rf /streamlink-saa-patches && \
    cd /saa && \
    pip3 install . && \
    cd / && \
    rm -rf /saa

COPY saa /saa

VOLUME ["/download", "/config"]

CMD ["saa", "--config-file", "/config/config.yml", "--streamers-file", "/config/streamers.yml"]

