streamers:
  MyYoutubeStreamer:
    url: "https://www.youtube.com/user/MyYoutubeStreamer/live"
    name: "MyYoutubeStreamer"
    download_directory: "/download/MyYoutubeStreamer"
    split_time: 18000
    rclone:
        remote_dir: "DemoRemote:/MyYoutubeStreamer"